Repository newrelic/nr-integrations-builder, pull requests merged in 2018-05, with the labels that each got.

#22 Add events to definition conf
  scaffold/bindata.go
  scaffold/resource/tmpl/definition.yml.tmpl
Labels: risk:low

#23 Replace Redis with generic custom fake data
  scaffold/bindata.go
  scaffold/resource/tmpl/src/integration.go.tmpl
Labels: enhancement, risk:low

#24 Entity type arg
  cmd/init.go
  scaffold/bindata.go
  scaffold/resource/tmpl/src/integration_local.go.tmpl
  scaffold/resource/tmpl/src/integration_remote.go.tmpl
  scaffold/resource/tmpl/src/integration_test_local.go.tmpl
  scaffold/resource/tmpl/src/integration_test_remote.go.tmpl
  scaffold/scaffold.go
Labels: risk:medium

#26 Update vendors and args all
  scaffold/bindata.go
  scaffold/resource/tmpl/src/integration_local.go.tmpl
  scaffold/resource/tmpl/src/integration_remote.go.tmpl
  scaffold/resource/tmpl/vendor/vendor.json.tmpl
Labels: risk:low

#28 Update sdk and args.All
  scaffold/bindata.go
  scaffold/resource/tmpl/src/integration_local.go.tmpl
  scaffold/resource/tmpl/src/integration_remote.go.tmpl
  scaffold/resource/tmpl/vendor/vendor.json.tmpl
Labels: risk:low
